jfbetapipeorg/Org_test_Automation_PowerShell

tests/yaml/S_PS_R_FLSPEC_0019.yml
tests/yaml/S_PS_R_FLSPEC_0020.yml
tests/yaml/S_PS_R_FLSPEC_0021.yml

https://www.jfrog.com/jira/browse/PIPE-4410
- S-PS-R-FLSPEC-0019. User uses filespec with pattern, valid sortBy to ' +
'download input resources for a step in powershell and triggers the run ' +
'and sees the run is successful.
- S-PS-R-FLSPEC-0020. User uses filespec with pattern, valid excludePatterns to ' +
'download input resources for a step in powershell and triggers the run ' +
'and sees the run is successful.
-S-PS-R-FLSPEC-0021. User uses filespec with pattern, valid exclusions to ' +
'download input resources for a step in powershell and triggers the run ' +
'and sees the run is successful.

Add new FileSpec Test cases

---

tests/yaml/S_PS_UTIL_0073.yml
tests/yaml/S_PS_UTIL_0074.yml
tests/yaml/S_PS_UTIL_0075.yml
tests/yaml/S_PS_UTIL_0076.yml

PIPE-4961 - New write_output tests.

---

tests/yaml/EXT-S-PS-AU-0001.yml
tests/yaml/EXT-S-PS-AU-0002.yml
tests/yaml/EXT-S-PS-AU-0003.yml
tests/yaml/EXT-S-PS-AU-0004.yml
tests/yaml/EXT-S-PS-AU-0005.yml
tests/yaml/EXT-S-PS-AU-0006.yml
tests/yaml/EXT-S-PS-AU-0007.yml
tests/yaml/EXT-S-PS-AU-0008.yml
tests/yaml/EXT-S-PS-AU-0009.yml
tests/yaml/EXT-S-PS-AU-0010.yml
tests/yaml/EXT-S-PS-AU-0011.yml
tests/yaml/EXT-S-PS-AU-0012.yml
tests/yaml/EXT-S-PS-AU-0013.yml
tests/yaml/EXT-S-PS-AU-0014.yml
tests/yaml/EXT-S-PS-AU-0015.yml
tests/yaml/EXT-S-PS-AU-0016.yml
tests/yaml/EXT-S-PS-AU-0017.yml
tests/yaml/EXT-S-PS-AU-0018.yml

PowerShell UploadArtifact YMLs.

Adds UploadArtifact PowerShell tests.

---

tests/yaml/S_PS_Generic_0063.yml
tests/yaml/S_PS_Generic_0064.yml
tests/yaml/S_PS_Generic_0065.yml
tests/yaml/S_PS_R_IMAGE_0028.yml

Artifactory Docker registry images in resources and as the build image and that the new variables are set correctly.

Project build info tests.

---

tests/yaml/S_PS_Generic_0066.yml
tests/yaml/S_PS_Generic_0067.yml
tests/yaml/S_PS_Generic_0068.yml

Checks that the step does and does not use the version of the CLI in the image, depending on the value of `USE_LOCAL_JFROG_CLI`.

PIPE-5472 PowerShell tests.

---

tests/yaml/S_PS_R_GIT_0033.yml

Checks that the clone is on the right branch and the right depth.

GitRepo shallow clone test.

---

tests/yaml/S_PS_LinuxVMDeploy_0001.yml
tests/yaml/S_PS_LinuxVMDeploy_0002.yml
tests/yaml/S_PS_LinuxVMDeploy_0003.yml
tests/yaml/S_PS_LinuxVMDeploy_0004.yml
tests/yaml/S_PS_LinuxVMDeploy_0005.yml
tests/yaml/S_PS_LinuxVMDeploy_0006.yml
tests/yaml/S_PS_LinuxVMDeploy_0007.yml

PIPE-5544 Tests for releaseBundle in LinuxVmDeploy

---

tests/yaml/S_PS_GoPublishBinary_0001.yml
tests/yaml/S_PS_GoPublishBinary_0002.yml
tests/yaml/S_PS_GoPublishBinary_0003.yml
tests/yaml/S_PS_GoPublishBinary_0004.yml

Just sync test cases involving PowerShell steps.

Go sync tests.

---

tests/yaml/S_PS_Generic_5816_001.yml

New affinityGroup test.

---

tests/yaml/S_PS_Generic_6237_001.yml

Test case to check that missing release bundle name and number is caught as intended.

PIPE-6237 - New save_artifact_info test.

---

tests/yaml/S_PS_CreateReleaseBundle_0001.yml
tests/yaml/S_PS_CreateReleaseBundle_0002.yml
tests/yaml/S_PS_CreateReleaseBundle_0003.yml
tests/yaml/S_PS_CreateReleaseBundle_6237_001.yml
tests/yaml/S_PS_CreateReleaseBundle_6237_002.yml
tests/yaml/S_PS_CreateReleaseBundle_6237_003.yml
tests/yaml/S_PS_CreateReleaseBundle_6237_004.yml
tests/yaml/S_PS_CreateReleaseBundle_6237_005.yml
tests/yaml/S_PS_CreateReleaseBundle_6237_006.yml
tests/yaml/S_PS_CreateReleaseBundle_6237_007.yml
tests/yaml/S_PS_CreateReleaseBundle_6237_008.yml
tests/yaml/S_PS_CreateReleaseBundle_6237_009.yml
tests/yaml/S_PS_CreateReleaseBundle_6237_010.yml
tests/yaml/S_PS_CreateReleaseBundle_6237_011.yml

Moves CreateReleaseBundle tests from Org_test_Automation.

Moves CreateReleaseBundle tests.

---

tests/helmCharts/myChart/Chart.yaml
tests/npm/index.js
tests/npm/package.json
tests/yaml/S_PS_HelmPublish_6191_001.yml
tests/yaml/S_PS_HelmPublish_6191_002.yml
tests/yaml/S_PS_HelmPublish_6191_003.yml
tests/yaml/S_PS_HelmPublish_6191_004.yml
tests/yaml/S_PS_HelmPublish_6191_005.yml
tests/yaml/S_PS_HelmPublish_6191_006.yml
tests/yaml/S_PS_HelmPublish_6191_007.yml
tests/yaml/S_PS_HelmPublish_6191_008.yml
tests/yaml/S_PS_HelmPublish_6191_009.yml
tests/yaml/S_PS_HelmPublish_6191_010.yml
tests/yaml/S_PS_HelmPublish_6191_011.yml
tests/yaml/S_PS_NpmPublish_6191_001.yml
tests/yaml/S_PS_NpmPublish_6191_002.yml
tests/yaml/S_PS_NpmPublish_6191_003.yml
tests/yaml/S_PS_NpmPublish_6191_004.yml
tests/yaml/S_PS_NpmPublish_6191_005.yml
tests/yaml/S_PS_NpmPublish_6191_006.yml
tests/yaml/S_PS_NpmPublish_6191_007.yml
tests/yaml/S_PS_PublishBuildInfo_6191_001.yml

Mostly tests for existing NpmPublish and HelmPublish steps.

PowerShell tests for NpmPublish, HelmPublish, and PublishBuildInfo.

---

tests/yaml/S_PS_CreateReleaseBundle_6189_001.yml
tests/yaml/S_PS_CreateReleaseBundle_6189_002.yml
tests/yaml/S_PS_CreateReleaseBundle_6189_003.yml
tests/yaml/S_PS_CreateReleaseBundle_6189_004.yml
tests/yaml/S_PS_CreateReleaseBundle_6189_005.yml

PIPE-6189 - PowerShell CreateReleaseBundle tests.

---

tests/yaml/S_PS_LinuxVMDeploy_0001.yml
tests/yaml/S_PS_LinuxVMDeploy_0002.yml
tests/yaml/S_PS_LinuxVMDeploy_0004.yml
tests/yaml/S_PS_LinuxVMDeploy_0005.yml
tests/yaml/S_PS_LinuxVMDeploy_0006.yml
tests/yaml/S_PS_LinuxVMDeploy_0007.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0008.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0009.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0010.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0011.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0012.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0013.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0014.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0015.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0016.yml

Tests for linuxVMDeploy rollingUpdate redesign.

PIPE-5950 Tests for linuxVMdeploy bluegreen strat.

---

tests/yaml/S_PS_CreateReleaseBundle_6237_011.yml
tests/yaml/S_PS_DockerPush_6190_001.yml
tests/yaml/S_PS_DockerPush_6190_002.yml
tests/yaml/S_PS_Generic_6187_001.yml
tests/yaml/S_PS_Generic_6187_002.yml
tests/yaml/S_PS_GoPublishBinary_6187_001.yml
tests/yaml/S_PS_GoPublishBinary_6187_002.yml
tests/yaml/S_PS_GoPublishModule_6284_0001.yml
tests/yaml/S_PS_GradleBuild_6188_001.yml
tests/yaml/S_PS_HelmPublish_6191_001.yml
tests/yaml/S_PS_HelmPublish_6191_002.yml
tests/yaml/S_PS_MvnBuild_6188_001.yml
tests/yaml/S_PS_NpmPublish_6191_001.yml
tests/yaml/S_PS_NpmPublish_6191_002.yml
tests/yaml/S_PS_PublishBuildInfo_6191_001.yml

Fix builder token headers.

---

tests/yaml/S_PS_UTIL_6379_001.yml

Checks that the variables are saved.

PIPE-6379 - PowerShell test.

---

tests/yaml/S_PS_UTIL_6379_001.yml
tests/yaml/S_PS_UTIL_6380_001.yml
tests/yaml/S_PS_UTIL_6380_002.yml
tests/yaml/S_PS_UTIL_6380_003.yml
tests/yaml/S_PS_UTIL_6380_004.yml
tests/yaml/S_PS_UTIL_6380_005.yml
tests/yaml/S_PS_UTIL_6380_006.yml
tests/yaml/S_PS_UTIL_6380_007.yml
tests/yaml/S_PS_UTIL_6380_008.yml
tests/yaml/S_PS_UTIL_6380_009.yml
tests/yaml/S_PS_UTIL_6380_010.yml
tests/yaml/S_PS_UTIL_6380_011.yml
tests/yaml/S_PS_UTIL_6380_012.yml
tests/yaml/S_PS_UTIL_6380_013.yml

Test cases for 6380 PowerShell utility functions.

Feature pipe 6380

---

tests/yaml/S_PS_UTIL_5961_001.yml

Same as Bash, but for PowerShell.

PIPE-5961 - Pull request branch filters.

---

tests/yaml/S_PS_GoPublishModule_6679_001.yml
tests/yaml/S_PS_MvnBuild_6679_001.yml

PIPE-7122 Tests for printing xray scan results and

---

tests/yaml/S_PS_DockerPush_6679_001.yml
tests/yaml/S_PS_GoPublishBinary_6679_001.yml
tests/yaml/S_PS_GoPublishModule_6679_001.yml
tests/yaml/S_PS_GradleBuild_6679_001.yml
tests/yaml/S_PS_MvnBuild_6679_001.yml
tests/yaml/S_PS_NpmPublish_6679_001.yml
tests/yaml/S_PS_PublishBuildInfo_6679_001.yml
tests/yaml/S_PS_XrayScan_6679_001.yml

tests can pass multiple times in a row.

PIPE-7154 make build ids unique so build-scan

---

tests/yaml/S_PS_Generic_2647_0001.yml

steps to fail on reports parsing when there were no testreports.

PE-2647 Fix bug where ps1 save_tests caused

---

tests/yaml/S_PS_LinuxVMDeploy_0001.yml
tests/yaml/S_PS_LinuxVMDeploy_0002.yml
tests/yaml/S_PS_LinuxVMDeploy_0003.yml
tests/yaml/S_PS_LinuxVMDeploy_0004.yml
tests/yaml/S_PS_LinuxVMDeploy_0005.yml
tests/yaml/S_PS_LinuxVMDeploy_0006.yml
tests/yaml/S_PS_LinuxVMDeploy_0007.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0008.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0009.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0010.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0011.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0012.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0013.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0014.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0015.yml
tests/yaml/S_PS_LinuxVMDeploy_5950_0016.yml

steps to fail on reports parsing when there were no testreports.

PIPE-2647 Fix bug where ps1 save_tests caused

---

tests/yaml/S_PS_R_INWEB_0003.yml
tests/yaml/S_PS_R_INWEB_0004.yml
tests/yaml/S_PS_R_INWEB_0005.yml
tests/yaml/S_PS_R_INWEB_0006.yml
tests/yaml/S_PS_R_INWEB_0007.yml
tests/yaml/S_PS_R_INWEB_0008.yml
tests/yaml/S_PS_R_INWEB_7906_001.yml
tests/yaml/S_PS_R_INWEB_7906_002.yml

Fixes existing YML files and adds two new test cases.

PIPE-7906 - Fix PowerShell IncomingWebhook YMLs.

---

tests/yaml/S_PS_I_Artifactory_0005.yml
tests/yaml/S_PS_R_INWEB_0001.yml
tests/yaml/S_PS_R_VM_0001.yml
tests/yaml/S_PS_R_VM_0002.yml
tests/yaml/S_PS_R_VM_0003.yml
tests/yaml/S_PS_R_VM_0004.yml
tests/yaml/S_PS_R_VM_0005.yml
tests/yaml/S_PS_R_VM_0006.yml
tests/yaml/S_PS_R_VM_0007.yml
tests/yaml/S_PS_R_VM_0008.yml
tests/yaml/S_PS_UTIL_0066.yml

changes from https://github.com/jfbetapipeorg/Org_test_Automation_PowerShell/pull/95 were missing in jfbetapipeorg/Org_test_Automation_PowerShell.

PIPE-7900 - Fix PowerShell tests.

---

tests/yaml/S_PS_UTIL_4075_001.yml

Just saves a test named total.xml.

PIPE-4075 - New save_tests test.

---

tests/yaml/S_PS_CreateReleaseBundle_7932_001.yml

New test case.  Just a CreateReleaseBundle with `sign:true`.

PIPE-7932 - New CreateReleaseBundle test case.

---

tests/npm/package.json
tests/yaml/S_PS_NpmPublish_6191_001.yml
tests/yaml/S_PS_NpmPublish_6191_002.yml
tests/yaml/S_PS_NpmPublish_6191_003.yml
tests/yaml/S_PS_NpmPublish_6191_004.yml
tests/yaml/S_PS_NpmPublish_6191_005.yml
tests/yaml/S_PS_NpmPublish_6191_006.yml
tests/yaml/S_PS_NpmPublish_6191_007.yml
tests/yaml/S_PS_NpmPublish_6679_001.yml
tests/yaml/S_PS_NpmPublish_8118_001.yml

Updates package.json used in NpmPublish tests to create unique versions.

PIPE-8118 - Make published Npm module versions unique.

---

tests/yaml/S_PS_I_JFrogPlatformToken_8032_0001.yml

PIPE-8032 - jfrog platform integration powershell tests

PIPE-8032 - jfrog platform integration tests

---

tests/yaml/S_PS_Generic_0033.yml
tests/yaml/S_PS_Generic_0036.yml
tests/yaml/S_PS_Generic_0039.yml

base language image version are updated https://git.jfrog.info/projects/PIP/repos/imagebuilds/browse/images/aws/x86_64/WindowsServer_2019/images.txt so updated yaml

Updated default powershell language images yaml

---

tests/yaml/S_PS_HelmDeploy_8138_001.yml
tests/yaml/S_PS_HelmPublish_8138_001.yml

Two new test cases, one HelmDeploy and one HelmPublish, with variables in values file paths.

PIPE-8138 - HelmDeploy and HelmPublish tests.

---

tests/yaml/S_PS_HelmDeploy_8138_002.yml
tests/yaml/S_PS_HelmPublish_8138_002.yml

Two new test cases and a slight modification to another of the new test cases.

PIPE-8138 - HelmDeploy and HelmPublish tests with invalid file paths.

---

tests/yaml/S_PS_DockerBuild_8307_001.yml
tests/yaml/S_PS_DockerPush_8307_001.yml
tests/yaml/S_PS_DockerPush_8307_002.yml
tests/yaml/S_PS_DockerPush_8307_003.yml
tests/yaml/S_PS_DockerPush_8307_004.yml
tests/yaml/S_PS_DockerPush_8307_005.yml
tests/yaml/S_PS_DockerPush_8307_006.yml
tests/yaml/S_PS_DockerPush_8307_007.yml
tests/yaml/S_PS_DockerPush_8307_008.yml
tests/yaml/S_PS_R_IMAGE_8307_001.yml
tests/yaml/S_PS_R_REFILE_8312_000.yml
tests/yaml/S_PS_R_REFILE_8312_001.yml
tests/yaml/S_PS_R_REFILE_8312_002.yml
tests/yaml/S_PS_R_REFILE_8312_003.yml
tests/yaml/S_PS_R_REFILE_8312_004.yml

RemoteFile test cases for PowerShell.

PIPE-8312 - RemoteFile tests.

---

tests/yaml/S_PS_NpmPublish_8304_007.yml

Non-default project Xray scan.

PIPE-8304 - NpmBuild and NpmPublish.

---

tests/yaml/S_PS_DockerPush_8307_007.yml
tests/yaml/S_PS_DockerPush_8307_009.yml

One new test case, two with one less step.

PIPE-8307 - DockerPush non-default project Xray scan.

---

tests/yaml/S_PS_DockerBuild_8307_001.yml

PIPE-8307 - Fix S_PS_DockerBuild_8307_001.

---

tests/yaml/S_PS_CreateReleaseBundle_8310_001.yml
tests/yaml/S_PS_CreateReleaseBundle_8310_002.yml
tests/yaml/S_PS_CreateReleaseBundle_8310_003.yml
tests/yaml/S_PS_CreateReleaseBundle_8310_004.yml
tests/yaml/S_PS_CreateReleaseBundle_8310_005.yml
tests/yaml/S_PS_CreateReleaseBundle_8310_006.yml
tests/yaml/S_PS_CreateReleaseBundle_8310_007.yml
tests/yaml/S_PS_CreateReleaseBundle_8310_008.yml
tests/yaml/S_PS_CreateReleaseBundle_8310_009.yml
tests/yaml/S_PS_CreateReleaseBundle_8310_010.yml

CreateReleaseBundle test cases.

PIPE-8310 - CreateReleaseBundle tests.

---

tests/helmCharts/myChart/Chart.yaml
tests/helmCharts/myChart/values.yaml
tests/yaml/S_PS_HelmPublish_6191_003.yml
tests/yaml/S_PS_HelmPublish_6191_004.yml
tests/yaml/S_PS_HelmPublish_6191_006.yml
tests/yaml/S_PS_HelmPublish_6191_007.yml
tests/yaml/S_PS_HelmPublish_6191_008.yml
tests/yaml/S_PS_HelmPublish_6191_010.yml
tests/yaml/S_PS_HelmPublish_6191_011.yml
tests/yaml/S_PS_HelmPublish_8138_002.yml
tests/yaml/S_PS_HelmPublish_8309_001.yml
tests/yaml/S_PS_HelmPublish_8309_002.yml
tests/yaml/S_PS_HelmPublish_8309_003.yml
tests/yaml/S_PS_HelmPublish_8309_004.yml

Updates most of the HelmPublish PowerShell tests (except 8138-001) to use unique versions.

PIPE-8309 - Update HelmPublish tests to use different version numbers.

---

tests/yaml/S_PS_DockerBuild_4748_001.yml
tests/yaml/S_PS_DockerBuild_4748_002.yml

PIPE-4748 - PowerShell DockerBuild tests.

---

tests/yaml/S_PS_HelmDeploy_8309_005.yml

PIPE-8309 - S_PS_HelmDeploy_8309_005.

---

tests/yaml/S_PS_UTIL_0066.yml
tests/yaml/S_PS_UTIL_0069.yml

Empty and without an XML file tests.

PIPE-9869 - Update PowerShell save_tests tests.

---

tests/yaml/S_PS_R_DISTRULE_0001.yml
tests/yaml/S_PS_R_DISTRULE_0002.yml
tests/yaml/S_PS_R_DISTRULE_0003.yml
tests/yaml/S_PS_R_DISTRULE_0004.yml
tests/yaml/S_PS_R_DISTRULE_0005.yml
tests/yaml/S_PS_R_DISTRULE_0006.yml

Add DistributionRule YMLs.
